version: '3'
services:
  marllib-gym:
    build: .
    volumes:
      - ./test.py:/app/test.py
      - ./requirements.txt:/app/requirements.txt
      - ./src:/app/src
    working_dir: /app  # Set the working directory to /app inside the container
    command: tail -f /dev/null